version: "3.9"

services:
  sahara-attire:
    build: .
    container_name: sahara-attire
    restart: always
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
